name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim-version: ['version-2-2', 'devel']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Nim ${{ matrix.nim-version }}
      uses: alaviss/setup-nim@0.1.1
      with:
        path: 'nim-${{ matrix.nim-version }}'
        version: ${{ matrix.nim-version }}
    
    - name: Install dependencies
      run: nimble install -y
    
    
    - name: Run tests
      run: nimble test
    
